### ISSUE TITLE
V Command - MT_FREE needs t determine KB or MB for large systems

### ISSUE THREAD

**Issue by NormanDunbar** [janbredenbeek/QL-MultiMon#3]
The call to MT_FREE around lines 3618 and onwards, will display a negative total on the final line output by the V command. The current code takes D1 and divides it by 1024 to get KB. If there is 60M or more free memory, the result is negative.

To alleviate this, I think we should test bit 15 of D1 and if set, divide again by 1024 and print an M rather than a K.

**Comment by janbredenbeek** [comment]
Fixed - >32MB free memory is displayed as MB not KB.
